### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by XShockinFireX** [Ragnok123/BedWarsPE#2]
Crash Dump:
 
===BEGIN CRASH DUMP===
eNrNPA1v27a2f4XPvUDbC9vxR+IkLnKBNEm33CWNX+2uw6YhoCXKViOJmijF8S723985h5REyWni
NLnDK4ZFOiQPz/cHJfk/rSyIRGvc390b7h32egfDdkukqUxb4/+0snUCQ62z68nxp+lZq92KhFJ8
gTC1jjN+x2hqm+WxuEuEmwmPvc6VeM3ezK4/T8/etpmGB/GCvW6/ZjJlr9+9BkR+ECKWnffC+8JT
NTnrRFxlIt1RqVsAd85uRZxdBACPRQqLwiCGRYPdv9qtJMwXQQwYzFwYdaUnkOj+HoCBCJZI90Zk
ESxynCBGXDJdO87JUqjsvLh/Byv7o0dW5CqTUX3J/sNLyskzECEtOHh4wXuuxCzlseIgLRnTksN7
lsTzzHEyvoAV64wwD3oPTjuRUSLz2KOp/Qennsp8HmqcgwcnnsV5RNOGD077EEqe4bTdB6edx9k7
htP2Hpw2Xco0o11HD8/LUjA3jfE+LQmUueMUdqUnHnx74jwEGIgb/7xPBb8hsyRCDrdbNQm5K8pV
w952qz4nHs+sZf1vL7vP8K4SEevFyOBw8LTVlilaSIZPQ3ISSiWs5bvfXp6EfC1Sx5nQX7DZiMfe
JBVJKl2IOUYK4PhZCrJsjX9rveqxN2/HNVxTkd6KtPMvN+VqeZpHyZu5lKHg8dvW7+3WArXNQwwR
MEsBZ0BOv9vzxC0QN8+D0GuNexBaUplJV8LE4UG7xZOApvV3uz2YtggyuO1t+Q8WpPwmDOa4prtP
GPKYY7xtfQliT64U+zhjs+N/fzn+1Pn5+PyKjbp9RrSw/VGvz94U0/bZjzISDEQSBXnEzrwAdcOQ
5cAFOHdvWP8tC/YORrBJskxgi73uqIt3f4oYWGsN4LanB6+lQhLOP36cAYBuVhBOy8CqKJDeqj7+
NQTTbduSXa/b6+4BhOcZuCYs+e13I6/fUK60FwgO/gJcxBxiC5Dh81CJdssTYJ+eWaSkn53agIhT
cL8M4sAP7gLpODIWt0qilq9i8bOC/2FCkBwZm1xNZ1+uPl2cAmgl5irIgN44D0Pg59gDgrNAQUj4
KXBvLH6aI+26WRD532bte1k65enNx6FSjtPYfwOwJX9+jSe/xkevO7R5aC3lOoij/m7ktmx++oNn
MARbAun+tuSGAVc2wXRfF/2gIfrWr9z9Eez7BWnGXR3nEu5OQq7UdrRDig7cHz+fWuSXoKbxjOoc
8DDIw/XLMaDxOc4y9zQbj3DQWmZZosY7OxC/lvm868poh4fiKwTZVAKunSqMdkwE2MlSIXZMVVby
CWI4gYiaXvDFwpJDBasLot9U5YWAMOxd+Zcnk7PWS/lUuTtkdRCCrhWfKA2bsJ2KHeRXRnOeXcjF
QqQ2yzb4EQO+4NFcvpz2CR1VdiUFW1mBseOTFOqKn8Ta9sMK1rTkeoRvnZx+4KErcavyssbY8DmK
LKj4bqMuaNqZVAZ9OelMTFZD7qmYPw4h1NYEYIPrMmj48tmtDKfAwMP6zNJ8a66trYtmoyTECGA6
O/40+zzZYB+4X61WXQE0IfpudoM8np5+nOry0bZYG2px2K9xB+KrB9rnGKrnxSrXO0J3Udt+Czs9
FbczqN9sLZWgRphpZuuWVj/UD4LNBI9qHA27/e9VVbE/cFNR8oiKGhZaUbZT4gBmz7haX17N7ORS
ghouyRvB5fSXFwwtp79Ae2c2/m4vBCwdCqQlC8ghuKWM1gObwwJULyuBh4Y2U/lVuNC0+1AQZi+Y
Ry+EgOajIKO62s5Ai9nQmSb3cEXgJmeDl+SsEuDWPCJR9bvteP2gm0EFBFus2tC6le7Nh3VOZyJb
ilR41y+nPWt3xzE326dBI4Pjyfmm7hDY1Fzvb9cctDtzanmEngz4S9VpCrdRXJ7G0DKfx17g8kza
CWFjqFHG1Bk21NQYHT1DeyV3viYjKMgAXW4StgWnPwoeZstpxmuJ3YY2i9NGmMGToxuRDnqH15eN
8rSZM57CqEWB49TJ2YKrAAwtA0Orac4C2jwBlY8kh8Pn5oZq5+dnB4sLYPQ8E9GZ78O9rT4barM6
6O41PfIXMJv1RmPxrAhzB7YJbVYgtmNWdXnW8bnbjUWGLP0UhCEoPM0shirYwwcOrff5zU2Q4YGY
ujx5sV6phtVxSmqe0kBc8Dx2lxPu2YqygI8whiqanP/wYiwZfND8lSQ8iRvIj8dAnc1LAapzMnxS
XTJ8dl1SkFFdbclRsFhmcRAv6Ni0pqTGyCPd+sfgRs7en7wgX/X98RS+SdBW/N2KabCI65wVsGYv
3v97jmJCIEAhAX/LgUzFLsjjksfrLzINa/5oAetxs9cdPi6R3gtIJAIKVkTBU9wRO6NPQgk7ZlYw
ixXQ7MOd63N4QMGnuCOQbm2+Df3ThK9qpllAGgXyNqcK/e8/VTC7NkX/UJd6z0mC7lZP4f8nUGjL
UFh8bY41nw70d+tMLvNIpLn6+mJq2iDhu51vA9MmRMsjyZONwyMb2kgZ/+WzI2vnbTX9DUXnqZiI
NKqxVcKaebDXOf94evZznbnR7ocPvd6LsXat8TlOSYZ1+fRjF1xpAmmFBRifBlESikv9YoPNfWPA
PjHrDmqMn+aZfLnQU9/XcTbo2CIITfP0Nrjl4Q/ESsWSDX7kkcUxZCIxWwqcm74Yc4QVeLII+f58
ibiypVgghTvKoMQ71OuMJzN5ah9WFJB6OtwoEF40j2Q8yaQnHafafAv1zYJImGfgtRPcOtzOhQ82
ffaj2Hb5fIL8mP7uPrcprNH1lGT/M/R/73lssVhAmtbZCKQ/RF8uX66GQ2yOY7YuL7Zn4ZNY8dRr
cGGAFiPDx89t21SgPVMd1e7b+xa41i0sS2lZN3IT0dV+RDUkvm5wXGtja+CNhu96LjJ+7Ynb61e9
3YNG03R2yZNL6XkvGFYSEfEkIpyOQzWnANKorW0Q+uS6oKJ2ZxrxMOz8elI8TqpV5LV9CrmZA46m
3ApwMxL1tivM28/MrEWBToJKNC1PqRO/s2epsV4dwF7w2Ns8gSVos3E5fPxEcvujVzxBfcLhawgE
laevhrrtT5mB7QSKtPUmo+VIk9nRSzJrCP4+1hNDYsm+RfMWIsBy62TJs0ZlSaBmYbm7bWH5WGdk
Fa8bnNYeW3yj4ETqqqtnl5uExJwIfuKZaBwIEqhuAP3/zsFF8WQU9Ivqu+RKBbfC6LVuIe3WDzL0
phkazice33xOWpsx5Aaox6f2f8upRymqsm7/wtNko2YnYFOavc0qL0hv1LPl+QFIo7clfSrJpqFc
WbdnSok4CwCNPpY20vPN7o6jiGJIuklR6Rvqt3khybz7bL2PVL4N/Y3H+5/4IpY3/cHw4TO9JyQT
s6XjVHt/21WK9gTYFD5IxNJcAXrk8Bjq/XmwUFEQil9OX65Mt7GCIgwx25ey+OYkT4EVMNNiL3ob
tWuCZ4C9ZevVpLxjJzL2gwXDN+Gd1IlffUgD9m8es8GA9Ufj/t64P2LHJzM26PVHOEHj66C8jtAx
T1LuZ6zopKwZiUyzo/5hfzhAYCQima47YRAF2dGg1+tdIhS7JKiXxFGP5vC7jn4DVx31CaLw8Khj
agNQxpGmYbUElgGXyvRCLezOH7lI10cytkApxJEj6fuEXmZeRfK4RjOPY5nHrjD7d7i7DMStiPA0
2GCEokuuOn6IR8UFSk0fjwMoyVQdGMl5CfFlCqhLZg10CSWuK9PyPrlNzFZe4PuBm4fZ+qiP9yGQ
EmqRU7FUwZQQ3tFub7eC4McSRx8ujmcIQva7CQRXWOYd/ZP+ASd5JjuK3wqzXSo8lUEk7rg8hF05
SVoP6beVM5nCThl+P6GONIGKxBvKBRqOmYwv9ZaRs7uOQjQ1hrbLXLKyPCXcZGwMhMLOI74IYFc8
3ATbY9DoK8GKrRhPBQOfYECbggueMRcVlbG5YEHshjnU13DBNmwccU3xRWXpI4ImTsV90WYS3wRQ
iJLN8YV6tpZ5anCxwGegq8APaAdQUwoWCJkGEH8UqxLdjid8DopSbCXj1xnjSSJ4ylDCEfAKrIVr
IB+ICJRme7UUMcuTRco9QNB1YnQYjWzsxOzVbAmZphMCCKiAam+R84Vg+FUJScw4lwrgPpSAP/iT
ZIpLT5bCNVzUFwIBRcoTcXcV3AQJNCa8K9PFDt7t4FcI19K/Pp9eXY+Gh53BNa4DMZaIxsyBmLZw
WrjRlyW9RcEyCfTEHgMumaLvHUBNmHXAhkBuNEzSJEoFfncDjJFKoSnDF8aXkHNDUnIEiLWfVFtS
7AS4WuaZJ9Gp9PETEqPfsmdTM/Q/mrJjdFKGkQG/9THJm90GnP0vBgeYQkGiSOtjhikGF06XsI6j
neIZKzMbaW1xg4jlCuwQIjnYAjEI5QnMhKTgoaiqgQ5QNpdKVOjPKBwVeIBphp7PwGLBKJDU+ZoZ
U4LpJniVo5UkXn2B2gP0CVbFPY+lQmnjQzLB3G6AHK6g0MPAxcDk5gLlAXIXf+Q8RI0soM6KGYS9
XLA3ZksI7m8Bud4PgqbA2N0BheI7nWMYxZ0/5tEcBA4edazWsTvj6gaMPr0BH+ri+GcFEkETLZjE
WcsU6rgcrAJmqzaj6MVMUAGrbYMYIpCawkxLYoF8hrAoj/GdC4AS7ilZDfAD/pXKOwi3mQARADtk
7XFJGkpVk3Puo5PiFHTGNguy1yC5LKVVnsCEQobYWMveAAf4dcgAJUI8dAyXY8KEDquTGbnrD6Gc
g2AxozMNZpTjMCxFYsHn6wwIYlNNSo8218FTOzvwtAqIMBI2wxxjcqUBKZKLH4C5QKSiD1UQiw9h
othRqx+YycloFxL4kOgdKDPYZ0FE6uQ7Zj2HogXF5QyiDff+n5OP1dEDxGMefRbxkPwS2t9Eq5Ie
g00xcCnMosIrqME9C5L6vcGupgoavUBSRkJfVLihSzHZUFf6Wx+2glDjoY3RjA42L9rTKJJLqNZj
8FCQG0aHb4lVixPKoZCCPPq6nuZQykUc4H2VJ+twhDtcYQjBJEfTu5uTkW1TxIIIE+FiLlQkFqRV
y1ivLRkASYpEVWwOe4ZP9fZeggzXQ831gqdz0H/HlWGoyz30sHulSuaEpJg1zKwB3414nFPWtamA
giQHW3jbLmJCwxiMNei4Sq/5EPaosrIuu9Ipj+7AIpYyD72SkAAiyCpmFelotywhyoHBERS8xCN7
9YE8YSM2kq3o1SVTfiqjIsTiWjPesaOSpVNgwqiuaQr32I+1Dstud5nHN0rL+4KsHgMiAZEybDyQ
G6bL4za5Zwo1iNKTOlgGYDlT4UJUhZqNoxyODJ2nUi9rqg+TABZLepmNQe9ipr0Az5SIoN4F29Vc
FxWt2QgHyuz9IConjkWGuiirNzCNUGfCOc+gj8BChGNZDAkQ7MlEJXJAXZuaUR2M5qLMiRRuXtnh
qxhBx0/XGeJus07fMmbMfbRtJytIgbCyN9JRpcq11CxgovN0uDMK1GsBaGjqsh+h3wHxHkE5DIZ7
MvnchrVAwRzizyrwsqWO2uTfJfoOoR+zfVMYVCWDIsFYU7vs2AN/WvLQ34E6X1cxngA7MxvBltr+
ZGw7ZJmdLVxWnXR2h86HZRAP29qxcWPzHWOXgdkIMm3M9Z8n8aSoFKqyHYsgXERPMLBmj5OOubVr
MuiGxDxfjE3R8S/Wx2LDZBasKmm4qCgVxbGlKCpNx6gC0khVJyq2ozKe5WAwOwtXixafailr06L/
q7UOoigikW7gRDdNNNWYF7JLCndBiBlZmFnS0UvGLIKhhWkpgCE6hEFy8bNApYMSr+GHyIlNWWZt
D8LMNqkhHyXVvfp4NTsbM4q68J+bQ38VQ39FiOj8CVVH5JmdS/JKFR/XtOVCKwGRxPBKVkQpCShB
q8nQcgY9k0IwlOnMhGaE7TDCTToyXl8HFzFM18JTdFdkcM6VsDZ70wdHuWeXNhvAQP++AZG53bfk
tErYVJA5zBAzdlfmWIQJCEx6P0z9WpPUx1YNLgYC6oKwesJwwMMVXyuN2+CxHUV3JuAbJoJACc4J
IwiMttNHDmVXYoarCFjLAGSIx5HMYzuFKFP1FWygAJAebDoguuPlmO1+eylP8bcDNDnmG+1a3mL9
w8G9q8k+Y6Gb0bnQ2ObCx1hG5zQY81CRJVZ9emMFTx07p/wW0jZWiAH23AIbuGRtzhdMNitLIgo1
Ph0WF4HVBEI/D2maVGDsHXTywNUCpiYuxaYeTAvQFqL6KrGX0t6leITWFlG0xRRV8l+GBa0MFGih
jEt+x3hTLuaDduFVFlXXBZn5J+4FubKWGT1wQx25uV5qLBfnQ72DUQ3PyTr6syvL3lz8plHbInbp
lRUVCZh+e6BkgP22B+F0//B3UxXTIRJGsACopqllKUYhSBNTSBrijUJPmJy81vVylScZnj5EIswo
hVIZN89TMgc8TmCUWxV5ZyXWqnEtJNvdFK2J7yse0BnEH7nIhbE+s57CGsE7CkxpzA6+C1sikzw0
2Mw1pt4GYiemmNMB3SLR+qyyQ1auUM+o6AhyUYanSgbaN+EPzwjHTBevhcHhDxnkCRRzuqLV7kLB
URdSBhdg2cdVZkNEuoe3K/zwrlMCCcajeQB+qaeY40l9BjHWwRaPS/DHFJiG6hrCmLD2LdOplMEb
va6DZ1h1SJkua9BkmQSxLysjXUq0TNqya51oQqFH9MUyXkfYxpD/KpCvKglFOzPDrBomgsETOOOL
BWRXc/hRHithDYw/KXFzPzeaHkSn7qMHPyPXZSyUPRyTp77B6gOMxzzIGDNzQUOgWWx7wcHwsgMZ
o0198O+IUQekoqawT0+phiiKf92BFSfE1FrddxhLnkcpSVH6RzuOoCoIgFCTry3SaVcigK4YnnCj
nVJ2qHYbMzzjHg/e7bf3Du/67eHdsD1413/nQVrVLvoGH9m56E5HBz22AGUqfbe795bOqgNz+Fyd
VptnNeIuEzFKip5pnUCusH7FYu5CzbEs5+K5ZuzxtALoXysqHvvQQ9ZyMQT4RTnmByF9GYufdekH
g36WlKNLMD797AlJxSKoHPqqam+VQ722TrJydDq5IJz43ZT05m6JJHHTirBPwjcdF4z/4xxELHz/
YO65o715by64f+Dvck+M/N7IP9g9ECNvd+j53sFgxP7RwqdKSj8cM+jANlEKnsVrtFZ/hPSLH+aK
7eG7uP2OJ25ZB58nDXp7vSFc0vZDd3RwMB/N5+6w5w1H3B9yd7jre97ufH++N98/2PfFHvyj7TN5
I2KIcEZ6+OMiQaI/Hhh08W3fP/Wvneh3WeD6zlKvJyMc6vWG/f4A3+WYnF6Zp3y7+ldYJktUKL3+
gFLUD0R/ubwod1t53l2Jz8YN19icWIQBZJUGmQX5IvhNKnytJBIVlL8VCpJWUM7Gm0wM9U+3dDR9
imKAqpbM9el7CVhzevhSfFyWmFMLw1O/R79TFV17MsNPhIqtIm1zBsevGHavJhT2Yco+igf3/3DW
+uuv/wOOX4fI
===END CRASH DUMP===

**Comment by erkam2002** [comment]
I can that fix

**Comment by majovec** [comment]
eee to si mysli ze se v tom vyznas ?

**Comment by majovec** [comment]
No shop stale nejde a ted uz se nedropuji ani itemi do truhly

**Comment by Creeperface01** [comment]
Thx for crash dump it will be VERY usefull for us

**Comment by majovec** [comment]
:D

**Comment by erkam2002** [comment]
Now go that

**Comment by erkam2002** [comment]
Download that again and test that

**Comment by Creeperface01** [comment]
i close this
