### ISSUE TITLE
Vilager

### ISSUE THREAD

**Issue by majovec** [Ragnok123/BedWarsPE#5]
hele v tom lobby vubec  nereaguje vesnican na pripojeni do areny funguje pouze na vybrani mapy a u prikazu /bw to napise "An uknown error occurred while attempting to perform this command" a pak shop stale nejde ukazuje to jao nabydku co si koupit ale nic vic a kdyz vyjedes z shopu tak kazdemu spadne MC:PE  
ale zaroven ti hazim sem to co to pise v konzoly snad to bude nejako platny 

critical> "Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'BedWars v1': Undefined property: BedWars\BedWarsGame::$Teams on BedWars\EventListener
[21:42:10] notice> UndefinedPropertyException: "Undefined property: BedWars\BedWarsGame::$Teams" (E_NOTICE) in "/phar_BedWarsPE-master_Mt0O1EjqyofxWw5.phar/src/BedWars/EventListener" at line 341

GOOD LUCK :D

**Comment by Ragnok123** [comment]
Porad nezapominam o bedwars pro vsechny. Ale pochop, ze musim delat i jine projekty. Novy bw update bude

**Comment by majovec** [comment]
hele Olegu ja vim ale tot je jen tak pro jistotu ale aspon nekdo se chopil toho ruskyho bw
