### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by atTheDisco** [Ragnok123/BedWarsPE#8]
[CRITICAL]: "Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'BedWars v1': Undefined property: BedWars\BedWarsGame::$Teams on BedWars\EventListener

[NOTICE]: UndefinedPropertyException: "Undefined property: BedWars\BedWarsGame::$Teams" (E_NOTICE) in "/BedWarsPE-master/src/BedWars/EventListener" at line 341

when asked to choose a team it gives this error

**Comment by erkam2002** [comment]
you must wait for new coding

**Comment by atTheDisco** [comment]
[CRITICAL]: "Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'BedWars': Undefined index: atthedisco on BedWars\EventListener

[NOTICE]: ArrayOutOfBoundsException: "Undefined index: atthedisco" (E_NOTICE) in "/Bedwars/src/BedWars/BedWars" at line 1

"InventoryTransactionEvent" how you'll solve the problem?

**Comment by erkam2002** [comment]
Crash?

**Comment by krendell** [comment]
Tap for Member Chest, exit Minecraft for Block Launcher

**Comment by Creeperface01** [comment]
I wont't continue on this project due to bad code structure so maybe i'll release my bedwars plugin from minetox in the future

**Comment by erkam2002** [comment]
Ok

**Comment by krendell** [comment]
Ok
13 февр. 2016 г. 16:55 пользователь "erkam2002" <notifications@github.com>
написал:

**Comment by erkam2002** [comment]
?

**Comment by krendell** [comment]
And when you release your Bed Wars?
13 февр. 2016 г. 3:36 пользователь "Creeperface01" <notifications@github.com>
написал:

**Comment by krendell** [comment]
http://old.minetox.cz/ you?
13 февр. 2016 г. 19:44 пользователь "Sirius Mine" <89641960211d@gmail.com>
написал:

**Comment by krendell** [comment]
[Server] [07:14:24] [Server thread/CRITICAL]: Could not execute task
BedWars\ExecuteTask:
scandir(/storage/sdcard0/PocketMine/plugins/BedWars/levels): failed to open
dir: No such file or directory
[Server] [07:14:24] [Server thread/WARNING]: RuntimeException:
"scandir(/storage/sdcard0/PocketMine/plugins/BedWars/levels): failed to
open dir: No such file or directory" (E_WARNING) in
"/BedWarsPE-master/src/BedWars/BedWars" at line 816
13 февр. 2016 г. 19:44 пользователь "Sirius Mine" <89641960211d@gmail.com>
написал:
